// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"codeid.hr-api/internal/domain/model"
)

func newDependent(db *gorm.DB, opts ...gen.DOOption) dependent {
	_dependent := dependent{}

	_dependent.dependentDo.UseDB(db, opts...)
	_dependent.dependentDo.UseModel(&model.Dependent{})

	tableName := _dependent.dependentDo.TableName()
	_dependent.ALL = field.NewAsterisk(tableName)
	_dependent.DependentID = field.NewInt32(tableName, "dependent_id")
	_dependent.FirstName = field.NewString(tableName, "first_name")
	_dependent.LastName = field.NewString(tableName, "last_name")
	_dependent.Relationship = field.NewString(tableName, "relationship")
	_dependent.EmployeeID = field.NewInt32(tableName, "employee_id")

	_dependent.fillFieldMap()

	return _dependent
}

type dependent struct {
	dependentDo

	ALL          field.Asterisk
	DependentID  field.Int32
	FirstName    field.String
	LastName     field.String
	Relationship field.String
	EmployeeID   field.Int32

	fieldMap map[string]field.Expr
}

func (d dependent) Table(newTableName string) *dependent {
	d.dependentDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dependent) As(alias string) *dependent {
	d.dependentDo.DO = *(d.dependentDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dependent) updateTableName(table string) *dependent {
	d.ALL = field.NewAsterisk(table)
	d.DependentID = field.NewInt32(table, "dependent_id")
	d.FirstName = field.NewString(table, "first_name")
	d.LastName = field.NewString(table, "last_name")
	d.Relationship = field.NewString(table, "relationship")
	d.EmployeeID = field.NewInt32(table, "employee_id")

	d.fillFieldMap()

	return d
}

func (d *dependent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dependent) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 5)
	d.fieldMap["dependent_id"] = d.DependentID
	d.fieldMap["first_name"] = d.FirstName
	d.fieldMap["last_name"] = d.LastName
	d.fieldMap["relationship"] = d.Relationship
	d.fieldMap["employee_id"] = d.EmployeeID
}

func (d dependent) clone(db *gorm.DB) dependent {
	d.dependentDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dependent) replaceDB(db *gorm.DB) dependent {
	d.dependentDo.ReplaceDB(db)
	return d
}

type dependentDo struct{ gen.DO }

type IDependentDo interface {
	gen.SubQuery
	Debug() IDependentDo
	WithContext(ctx context.Context) IDependentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDependentDo
	WriteDB() IDependentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDependentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDependentDo
	Not(conds ...gen.Condition) IDependentDo
	Or(conds ...gen.Condition) IDependentDo
	Select(conds ...field.Expr) IDependentDo
	Where(conds ...gen.Condition) IDependentDo
	Order(conds ...field.Expr) IDependentDo
	Distinct(cols ...field.Expr) IDependentDo
	Omit(cols ...field.Expr) IDependentDo
	Join(table schema.Tabler, on ...field.Expr) IDependentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDependentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDependentDo
	Group(cols ...field.Expr) IDependentDo
	Having(conds ...gen.Condition) IDependentDo
	Limit(limit int) IDependentDo
	Offset(offset int) IDependentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDependentDo
	Unscoped() IDependentDo
	Create(values ...*model.Dependent) error
	CreateInBatches(values []*model.Dependent, batchSize int) error
	Save(values ...*model.Dependent) error
	First() (*model.Dependent, error)
	Take() (*model.Dependent, error)
	Last() (*model.Dependent, error)
	Find() ([]*model.Dependent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Dependent, err error)
	FindInBatches(result *[]*model.Dependent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Dependent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDependentDo
	Assign(attrs ...field.AssignExpr) IDependentDo
	Joins(fields ...field.RelationField) IDependentDo
	Preload(fields ...field.RelationField) IDependentDo
	FirstOrInit() (*model.Dependent, error)
	FirstOrCreate() (*model.Dependent, error)
	FindByPage(offset int, limit int) (result []*model.Dependent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDependentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dependentDo) Debug() IDependentDo {
	return d.withDO(d.DO.Debug())
}

func (d dependentDo) WithContext(ctx context.Context) IDependentDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dependentDo) ReadDB() IDependentDo {
	return d.Clauses(dbresolver.Read)
}

func (d dependentDo) WriteDB() IDependentDo {
	return d.Clauses(dbresolver.Write)
}

func (d dependentDo) Session(config *gorm.Session) IDependentDo {
	return d.withDO(d.DO.Session(config))
}

func (d dependentDo) Clauses(conds ...clause.Expression) IDependentDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dependentDo) Returning(value interface{}, columns ...string) IDependentDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dependentDo) Not(conds ...gen.Condition) IDependentDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dependentDo) Or(conds ...gen.Condition) IDependentDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dependentDo) Select(conds ...field.Expr) IDependentDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dependentDo) Where(conds ...gen.Condition) IDependentDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dependentDo) Order(conds ...field.Expr) IDependentDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dependentDo) Distinct(cols ...field.Expr) IDependentDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dependentDo) Omit(cols ...field.Expr) IDependentDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dependentDo) Join(table schema.Tabler, on ...field.Expr) IDependentDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dependentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDependentDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dependentDo) RightJoin(table schema.Tabler, on ...field.Expr) IDependentDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dependentDo) Group(cols ...field.Expr) IDependentDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dependentDo) Having(conds ...gen.Condition) IDependentDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dependentDo) Limit(limit int) IDependentDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dependentDo) Offset(offset int) IDependentDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dependentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDependentDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dependentDo) Unscoped() IDependentDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dependentDo) Create(values ...*model.Dependent) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dependentDo) CreateInBatches(values []*model.Dependent, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dependentDo) Save(values ...*model.Dependent) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dependentDo) First() (*model.Dependent, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dependent), nil
	}
}

func (d dependentDo) Take() (*model.Dependent, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dependent), nil
	}
}

func (d dependentDo) Last() (*model.Dependent, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dependent), nil
	}
}

func (d dependentDo) Find() ([]*model.Dependent, error) {
	result, err := d.DO.Find()
	return result.([]*model.Dependent), err
}

func (d dependentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Dependent, err error) {
	buf := make([]*model.Dependent, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dependentDo) FindInBatches(result *[]*model.Dependent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dependentDo) Attrs(attrs ...field.AssignExpr) IDependentDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dependentDo) Assign(attrs ...field.AssignExpr) IDependentDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dependentDo) Joins(fields ...field.RelationField) IDependentDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dependentDo) Preload(fields ...field.RelationField) IDependentDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dependentDo) FirstOrInit() (*model.Dependent, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dependent), nil
	}
}

func (d dependentDo) FirstOrCreate() (*model.Dependent, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dependent), nil
	}
}

func (d dependentDo) FindByPage(offset int, limit int) (result []*model.Dependent, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dependentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dependentDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dependentDo) Delete(models ...*model.Dependent) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dependentDo) withDO(do gen.Dao) *dependentDo {
	d.DO = *do.(*gen.DO)
	return d
}
