// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"codeid.hr-api/internal/domain/model"
)

func newEmployeeDocument(db *gorm.DB, opts ...gen.DOOption) employeeDocument {
	_employeeDocument := employeeDocument{}

	_employeeDocument.employeeDocumentDo.UseDB(db, opts...)
	_employeeDocument.employeeDocumentDo.UseModel(&model.EmployeeDocument{})

	tableName := _employeeDocument.employeeDocumentDo.TableName()
	_employeeDocument.ALL = field.NewAsterisk(tableName)
	_employeeDocument.EdocID = field.NewInt32(tableName, "edoc_id")
	_employeeDocument.FileName = field.NewString(tableName, "file_name")
	_employeeDocument.FileSize = field.NewFloat64(tableName, "file_size")
	_employeeDocument.FileType = field.NewString(tableName, "file_type")
	_employeeDocument.FileURL = field.NewString(tableName, "file_url")
	_employeeDocument.EmployeeID = field.NewInt32(tableName, "employee_id")
	_employeeDocument.CreatedDate = field.NewTime(tableName, "created_date")
	_employeeDocument.ModifiedDate = field.NewTime(tableName, "modified_date")

	_employeeDocument.fillFieldMap()

	return _employeeDocument
}

type employeeDocument struct {
	employeeDocumentDo

	ALL          field.Asterisk
	EdocID       field.Int32
	FileName     field.String
	FileSize     field.Float64
	FileType     field.String
	FileURL      field.String
	EmployeeID   field.Int32
	CreatedDate  field.Time
	ModifiedDate field.Time

	fieldMap map[string]field.Expr
}

func (e employeeDocument) Table(newTableName string) *employeeDocument {
	e.employeeDocumentDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e employeeDocument) As(alias string) *employeeDocument {
	e.employeeDocumentDo.DO = *(e.employeeDocumentDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *employeeDocument) updateTableName(table string) *employeeDocument {
	e.ALL = field.NewAsterisk(table)
	e.EdocID = field.NewInt32(table, "edoc_id")
	e.FileName = field.NewString(table, "file_name")
	e.FileSize = field.NewFloat64(table, "file_size")
	e.FileType = field.NewString(table, "file_type")
	e.FileURL = field.NewString(table, "file_url")
	e.EmployeeID = field.NewInt32(table, "employee_id")
	e.CreatedDate = field.NewTime(table, "created_date")
	e.ModifiedDate = field.NewTime(table, "modified_date")

	e.fillFieldMap()

	return e
}

func (e *employeeDocument) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *employeeDocument) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 8)
	e.fieldMap["edoc_id"] = e.EdocID
	e.fieldMap["file_name"] = e.FileName
	e.fieldMap["file_size"] = e.FileSize
	e.fieldMap["file_type"] = e.FileType
	e.fieldMap["file_url"] = e.FileURL
	e.fieldMap["employee_id"] = e.EmployeeID
	e.fieldMap["created_date"] = e.CreatedDate
	e.fieldMap["modified_date"] = e.ModifiedDate
}

func (e employeeDocument) clone(db *gorm.DB) employeeDocument {
	e.employeeDocumentDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e employeeDocument) replaceDB(db *gorm.DB) employeeDocument {
	e.employeeDocumentDo.ReplaceDB(db)
	return e
}

type employeeDocumentDo struct{ gen.DO }

type IEmployeeDocumentDo interface {
	gen.SubQuery
	Debug() IEmployeeDocumentDo
	WithContext(ctx context.Context) IEmployeeDocumentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEmployeeDocumentDo
	WriteDB() IEmployeeDocumentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEmployeeDocumentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEmployeeDocumentDo
	Not(conds ...gen.Condition) IEmployeeDocumentDo
	Or(conds ...gen.Condition) IEmployeeDocumentDo
	Select(conds ...field.Expr) IEmployeeDocumentDo
	Where(conds ...gen.Condition) IEmployeeDocumentDo
	Order(conds ...field.Expr) IEmployeeDocumentDo
	Distinct(cols ...field.Expr) IEmployeeDocumentDo
	Omit(cols ...field.Expr) IEmployeeDocumentDo
	Join(table schema.Tabler, on ...field.Expr) IEmployeeDocumentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEmployeeDocumentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEmployeeDocumentDo
	Group(cols ...field.Expr) IEmployeeDocumentDo
	Having(conds ...gen.Condition) IEmployeeDocumentDo
	Limit(limit int) IEmployeeDocumentDo
	Offset(offset int) IEmployeeDocumentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEmployeeDocumentDo
	Unscoped() IEmployeeDocumentDo
	Create(values ...*model.EmployeeDocument) error
	CreateInBatches(values []*model.EmployeeDocument, batchSize int) error
	Save(values ...*model.EmployeeDocument) error
	First() (*model.EmployeeDocument, error)
	Take() (*model.EmployeeDocument, error)
	Last() (*model.EmployeeDocument, error)
	Find() ([]*model.EmployeeDocument, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EmployeeDocument, err error)
	FindInBatches(result *[]*model.EmployeeDocument, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EmployeeDocument) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEmployeeDocumentDo
	Assign(attrs ...field.AssignExpr) IEmployeeDocumentDo
	Joins(fields ...field.RelationField) IEmployeeDocumentDo
	Preload(fields ...field.RelationField) IEmployeeDocumentDo
	FirstOrInit() (*model.EmployeeDocument, error)
	FirstOrCreate() (*model.EmployeeDocument, error)
	FindByPage(offset int, limit int) (result []*model.EmployeeDocument, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEmployeeDocumentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e employeeDocumentDo) Debug() IEmployeeDocumentDo {
	return e.withDO(e.DO.Debug())
}

func (e employeeDocumentDo) WithContext(ctx context.Context) IEmployeeDocumentDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e employeeDocumentDo) ReadDB() IEmployeeDocumentDo {
	return e.Clauses(dbresolver.Read)
}

func (e employeeDocumentDo) WriteDB() IEmployeeDocumentDo {
	return e.Clauses(dbresolver.Write)
}

func (e employeeDocumentDo) Session(config *gorm.Session) IEmployeeDocumentDo {
	return e.withDO(e.DO.Session(config))
}

func (e employeeDocumentDo) Clauses(conds ...clause.Expression) IEmployeeDocumentDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e employeeDocumentDo) Returning(value interface{}, columns ...string) IEmployeeDocumentDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e employeeDocumentDo) Not(conds ...gen.Condition) IEmployeeDocumentDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e employeeDocumentDo) Or(conds ...gen.Condition) IEmployeeDocumentDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e employeeDocumentDo) Select(conds ...field.Expr) IEmployeeDocumentDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e employeeDocumentDo) Where(conds ...gen.Condition) IEmployeeDocumentDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e employeeDocumentDo) Order(conds ...field.Expr) IEmployeeDocumentDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e employeeDocumentDo) Distinct(cols ...field.Expr) IEmployeeDocumentDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e employeeDocumentDo) Omit(cols ...field.Expr) IEmployeeDocumentDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e employeeDocumentDo) Join(table schema.Tabler, on ...field.Expr) IEmployeeDocumentDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e employeeDocumentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEmployeeDocumentDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e employeeDocumentDo) RightJoin(table schema.Tabler, on ...field.Expr) IEmployeeDocumentDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e employeeDocumentDo) Group(cols ...field.Expr) IEmployeeDocumentDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e employeeDocumentDo) Having(conds ...gen.Condition) IEmployeeDocumentDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e employeeDocumentDo) Limit(limit int) IEmployeeDocumentDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e employeeDocumentDo) Offset(offset int) IEmployeeDocumentDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e employeeDocumentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEmployeeDocumentDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e employeeDocumentDo) Unscoped() IEmployeeDocumentDo {
	return e.withDO(e.DO.Unscoped())
}

func (e employeeDocumentDo) Create(values ...*model.EmployeeDocument) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e employeeDocumentDo) CreateInBatches(values []*model.EmployeeDocument, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e employeeDocumentDo) Save(values ...*model.EmployeeDocument) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e employeeDocumentDo) First() (*model.EmployeeDocument, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmployeeDocument), nil
	}
}

func (e employeeDocumentDo) Take() (*model.EmployeeDocument, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmployeeDocument), nil
	}
}

func (e employeeDocumentDo) Last() (*model.EmployeeDocument, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmployeeDocument), nil
	}
}

func (e employeeDocumentDo) Find() ([]*model.EmployeeDocument, error) {
	result, err := e.DO.Find()
	return result.([]*model.EmployeeDocument), err
}

func (e employeeDocumentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EmployeeDocument, err error) {
	buf := make([]*model.EmployeeDocument, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e employeeDocumentDo) FindInBatches(result *[]*model.EmployeeDocument, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e employeeDocumentDo) Attrs(attrs ...field.AssignExpr) IEmployeeDocumentDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e employeeDocumentDo) Assign(attrs ...field.AssignExpr) IEmployeeDocumentDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e employeeDocumentDo) Joins(fields ...field.RelationField) IEmployeeDocumentDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e employeeDocumentDo) Preload(fields ...field.RelationField) IEmployeeDocumentDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e employeeDocumentDo) FirstOrInit() (*model.EmployeeDocument, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmployeeDocument), nil
	}
}

func (e employeeDocumentDo) FirstOrCreate() (*model.EmployeeDocument, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmployeeDocument), nil
	}
}

func (e employeeDocumentDo) FindByPage(offset int, limit int) (result []*model.EmployeeDocument, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e employeeDocumentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e employeeDocumentDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e employeeDocumentDo) Delete(models ...*model.EmployeeDocument) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *employeeDocumentDo) withDO(do gen.Dao) *employeeDocumentDo {
	e.DO = *do.(*gen.DO)
	return e
}
