// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCountry = "countries"

// Country mapped from table <countries>
type Country struct {
	CountryID   string  `gorm:"column:country_id;type:character(2);primaryKey" json:"country_id"`
	CountryName *string `gorm:"column:country_name;type:character varying(40)" json:"country_name"`
	RegionID    int32   `gorm:"column:region_id;type:integer;not null" json:"region_id"`
}

// TableName Country's table name
func (*Country) TableName() string {
	return TableNameCountry
}
