// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDepartment = "departments"

// Department mapped from table <departments>
type Department struct {
	DepartmentID   int32  `gorm:"column:department_id;type:integer;primaryKey;autoIncrement:true" json:"department_id"`
	DepartmentName string `gorm:"column:department_name;type:character varying(30);not null" json:"department_name"`
	LocationID     *int32 `gorm:"column:location_id;type:integer" json:"location_id"`
}

// TableName Department's table name
func (*Department) TableName() string {
	return TableNameDepartment
}
