// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDependent = "dependents"

// Dependent mapped from table <dependents>
type Dependent struct {
	DependentID  int32  `gorm:"column:dependent_id;type:integer;primaryKey;autoIncrement:true" json:"dependent_id"`
	FirstName    string `gorm:"column:first_name;type:character varying(50);not null" json:"first_name"`
	LastName     string `gorm:"column:last_name;type:character varying(50);not null" json:"last_name"`
	Relationship string `gorm:"column:relationship;type:character varying(25);not null" json:"relationship"`
	EmployeeID   int32  `gorm:"column:employee_id;type:integer;not null" json:"employee_id"`
}

// TableName Dependent's table name
func (*Dependent) TableName() string {
	return TableNameDependent
}
