// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmployeeDocument = "employee_documents"

// EmployeeDocument mapped from table <employee_documents>
type EmployeeDocument struct {
	EdocID       int32      `gorm:"column:edoc_id;type:integer;primaryKey;autoIncrement:true" json:"edoc_id"`
	FileName     *string    `gorm:"column:file_name;type:text" json:"file_name"`
	FileSize     *float64   `gorm:"column:file_size;type:double precision" json:"file_size"`
	FileType     *string    `gorm:"column:file_type;type:character varying(15)" json:"file_type"`
	FileURL      *string    `gorm:"column:file_url;type:text" json:"file_url"`
	EmployeeID   *int32     `gorm:"column:employee_id;type:integer" json:"employee_id"`
	CreatedDate  *time.Time `gorm:"column:created_date;type:timestamp without time zone" json:"created_date"`
	ModifiedDate *time.Time `gorm:"column:modified_date;type:timestamp without time zone" json:"modified_date"`
}

// TableName EmployeeDocument's table name
func (*EmployeeDocument) TableName() string {
	return TableNameEmployeeDocument
}
