// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmployee = "hr.employees"

// Employee mapped from table <employees>
type Employee struct {
	EmployeeID   int32     `gorm:"column:employee_id;type:integer;primaryKey;autoIncrement:true" json:"employee_id"`
	FirstName    *string   `gorm:"column:first_name;type:character varying(20)" json:"first_name"`
	LastName     string    `gorm:"column:last_name;type:character varying(25);not null" json:"last_name"`
	Email        string    `gorm:"column:email;type:character varying(100);not null" json:"email"`
	PhoneNumber  *string   `gorm:"column:phone_number;type:character varying(20)" json:"phone_number"`
	HireDate     time.Time `gorm:"column:hire_date;type:date;not null" json:"hire_date"`
	JobID        int32     `gorm:"column:job_id;type:integer;not null" json:"job_id"`
	Salary       float64   `gorm:"column:salary;type:numeric(8,2);not null" json:"salary"`
	ManagerID    *int32    `gorm:"column:manager_id;type:integer" json:"manager_id"`
	DepartmentID *int32    `gorm:"column:department_id;type:integer" json:"department_id"`
	PhotoProfile *string   `gorm:"column:photo_profile;type:text" json:"photo_profile"`
}

// TableName Employee's table name
func (*Employee) TableName() string {
	return TableNameEmployee
}
