// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameJob = "jobs"

// Job mapped from table <jobs>
type Job struct {
	JobID     int32    `gorm:"column:job_id;type:integer;primaryKey;autoIncrement:true" json:"job_id"`
	JobTitle  string   `gorm:"column:job_title;type:character varying(35);not null" json:"job_title"`
	MinSalary *float64 `gorm:"column:min_salary;type:numeric(8,2)" json:"min_salary"`
	MaxSalary *float64 `gorm:"column:max_salary;type:numeric(8,2)" json:"max_salary"`
}

// TableName Job's table name
func (*Job) TableName() string {
	return TableNameJob
}
