// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLocation = "locations"

// Location mapped from table <locations>
type Location struct {
	LocationID    int32   `gorm:"column:location_id;type:integer;primaryKey;autoIncrement:true" json:"location_id"`
	StreetAddress *string `gorm:"column:street_address;type:character varying(40)" json:"street_address"`
	PostalCode    *string `gorm:"column:postal_code;type:character varying(12)" json:"postal_code"`
	City          string  `gorm:"column:city;type:character varying(30);not null" json:"city"`
	StateProvince *string `gorm:"column:state_province;type:character varying(25)" json:"state_province"`
	CountryID     string  `gorm:"column:country_id;type:character(2);not null" json:"country_id"`
}

// TableName Location's table name
func (*Location) TableName() string {
	return TableNameLocation
}
