// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	RoleID   int32   `gorm:"column:role_id;type:integer;primaryKey;autoIncrement:true" json:"role_id"`
	RoleName *string `gorm:"column:role_name;type:character varying(35)" json:"role_name"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
