// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID        int32      `gorm:"column:user_id;type:integer;primaryKey;autoIncrement:true" json:"user_id"`
	UserName      *string    `gorm:"column:user_name;type:character varying(15)" json:"user_name"`
	UserEmail     *string    `gorm:"column:user_email;type:character varying(80)" json:"user_email"`
	UserPassword  *string    `gorm:"column:user_password;type:character varying(125)" json:"user_password"`
	UserHandphone *string    `gorm:"column:user_handphone;type:character varying(15)" json:"user_handphone"`
	CreatedOn     *time.Time `gorm:"column:created_on;type:timestamp without time zone" json:"created_on"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
